/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.sysdev.softcpa.View.Payment;

import fr.sysdev.softcpa.constants.FR.*;
import fr.sysdev.softcpa.entity.Payment;

/**
 *
 * @author f
 */
public class PaymentDetailsView extends javax.swing.JInternalFrame {
private Payment payment;
    /**
     * Creates new form PaymentDetailsView
     */
    public PaymentDetailsView() {
        initComponents();
    }

    public PaymentDetailsView(Payment payment) {
        this.payment = payment;
        initComponents();
        this.title = Constants.Labels.PAYMENT_DETAILS;
        prepareForm();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_PaymentNumber = new javax.swing.JLabel();
        jLabel_PaymentNumber_Value = new javax.swing.JLabel();
        jLabel_Payment_Date = new javax.swing.JLabel();
        jLabel_Payment_Date_Value = new javax.swing.JLabel();
        jLabel_Payment_Amount = new javax.swing.JLabel();
        jLabel_Payment_Amount_Value = new javax.swing.JLabel();
        jLabel_Payment_Method = new javax.swing.JLabel();
        jLabel_Payment_Method_Value = new javax.swing.JLabel();

        jLabel_PaymentNumber.setText("jLabel1");

        jLabel_PaymentNumber_Value.setText("jLabel1");

        jLabel_Payment_Date.setText("jLabel1");

        jLabel_Payment_Date_Value.setText("jLabel1");

        jLabel_Payment_Amount.setText("jLabel1");

        jLabel_Payment_Amount_Value.setText("jLabel1");

        jLabel_Payment_Method.setText("jLabel1");

        jLabel_Payment_Method_Value.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Payment_Method)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Payment_Method_Value)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Payment_Amount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Payment_Amount_Value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_PaymentNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_PaymentNumber_Value)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel_Payment_Date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Payment_Date_Value)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PaymentNumber)
                    .addComponent(jLabel_PaymentNumber_Value)
                    .addComponent(jLabel_Payment_Date)
                    .addComponent(jLabel_Payment_Date_Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Payment_Method)
                        .addComponent(jLabel_Payment_Method_Value))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Payment_Amount)
                        .addComponent(jLabel_Payment_Amount_Value)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Payment getPayment() {
        return payment;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_PaymentNumber;
    private javax.swing.JLabel jLabel_PaymentNumber_Value;
    private javax.swing.JLabel jLabel_Payment_Amount;
    private javax.swing.JLabel jLabel_Payment_Amount_Value;
    private javax.swing.JLabel jLabel_Payment_Date;
    private javax.swing.JLabel jLabel_Payment_Date_Value;
    private javax.swing.JLabel jLabel_Payment_Method;
    private javax.swing.JLabel jLabel_Payment_Method_Value;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        jLabel_PaymentNumber.setText(Constants.Labels.PAYMENT_NUMBER);
        jLabel_PaymentNumber_Value.setText(payment.getId()+"");
        jLabel_Payment_Amount.setText(Constants.Labels.AMOUNT);
        jLabel_Payment_Amount_Value.setText(payment.getAmount()+"");
        jLabel_Payment_Date.setText(Constants.Labels.PAYMENT_DATE);
        jLabel_Payment_Date_Value.setText(payment.getDateOfPayment().toString());
        jLabel_Payment_Method.setText(Constants.Labels.PAYMENT_METHOD);
        jLabel_Payment_Date_Value.setText(payment.getPaymentMethod().getName());
    }
}
