/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.sysdev.softcpa.View;

import fr.sysdev.softcpa.View.Piece.PieceView;
import fr.sysdev.softcpa.View.Client.ClientView;
import fr.sysdev.softcpa.Controller.DefaultController;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
/**
 *
 * @author COPCGRE
 */

public class DefaultView extends javax.swing.JFrame {
    @Autowired
    private DefaultController defaultController;
    @Autowired
    private ClientView clientView;
    @Autowired
    private PieceView pieceView;
    
    private HashMap<String, JInternalFrame> viewsMap;

    /**
     * Creates new form App
     */
    public DefaultView() {
        viewsMap = new HashMap<>();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jButton_Clients = new javax.swing.JButton();
        jButton_Facturation = new javax.swing.JButton();
        jButton_Devis = new javax.swing.JButton();
        jButton_Fournisseur = new javax.swing.JButton();
        jButton_Stock = new javax.swing.JButton();
        jButton_Avoirs = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Clients = new javax.swing.JMenu();
        jMenu_Stock = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftCpa");

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jButton_Clients.setText("Clients");
        jButton_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClientsActionPerformed(evt);
            }
        });

        jButton_Facturation.setText("Facturation");

        jButton_Devis.setText("Devis");

        jButton_Fournisseur.setText("Fournisseurs");

        jButton_Stock.setText("Stock");
        jButton_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StockActionPerformed(evt);
            }
        });

        jButton_Avoirs.setText("Avoirs");

        jMenu_Clients.setText("Clients");
        jMenu_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ClientsActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Clients);

        jMenu_Stock.setText("Stock");
        jMenuBar1.add(jMenu_Stock);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_Clients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Facturation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Devis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Avoirs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Fournisseur, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Facturation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Devis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Avoirs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(113, 113, 113)
                        .addComponent(jButton_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Clients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(jButton_Fournisseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDesktopPane))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ClientsActionPerformed
      

    }//GEN-LAST:event_jMenu_ClientsActionPerformed

    private void jButton_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClientsActionPerformed
        clientView = defaultController.gestionClients();
        try {
            addFrame(clientView);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_ClientsActionPerformed

    private void jButton_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StockActionPerformed
       pieceView = defaultController.gestionStock();
        try {
            addFrame(pieceView);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_StockActionPerformed

    public void addFrame(JInternalFrame view) throws PropertyVetoException {
           boolean open = false;
          
          for (Object frame : jDesktopPane.getAllFrames()) {
            if(frame.equals(view))
            {   view.setSelected(true);
                open = true;
                break;
            }
        }
          if(!open){
            view.setVisible(true);
            jDesktopPane.add(view);
            view.setSelected(true);
          }
          

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Avoirs;
    private javax.swing.JButton jButton_Clients;
    private javax.swing.JButton jButton_Devis;
    private javax.swing.JButton jButton_Facturation;
    private javax.swing.JButton jButton_Fournisseur;
    private javax.swing.JButton jButton_Stock;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Clients;
    private javax.swing.JMenu jMenu_Stock;
    // End of variables declaration//GEN-END:variables
}
