/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.sysdev.softcpa.View;

import fr.sysdev.softcpa.View.Part.PartView;
import fr.sysdev.softcpa.View.Client.ClientView;
import fr.sysdev.softcpa.Controller.DefaultController;
import fr.sysdev.softcpa.View.Invoice.InvoiceView;
import fr.sysdev.softcpa.View.Invoicing.InvoicingView;
import fr.sysdev.softcpa.View.Provider.ProviderView;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


/**
 *
 * @author COPCGRE
 */
@Component
public class DefaultView extends javax.swing.JFrame {

    @Autowired
    private DefaultController defaultController;
    @Autowired
    private ClientView clientView;
    @Autowired
    private PartView pieceView;
    @Autowired
    private InvoicingView invoicingView;
    @Autowired
    private ProviderView providerView;
    @Autowired
    private InvoiceView invoiceView;

    private HashMap<String, JInternalFrame> viewsMap;

    /**
     * Creates new form App
     */
    public DefaultView() {
        viewsMap = new HashMap<>();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jButton_Clients = new javax.swing.JButton();
        jButton_Facturation = new javax.swing.JButton();
        jButton_Devis = new javax.swing.JButton();
        jButton_Providers = new javax.swing.JButton();
        jButton_Stock = new javax.swing.JButton();
        jButton_Avoirs = new javax.swing.JButton();
        jButton_Invoices = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Clients = new javax.swing.JMenu();
        jMenu_Stock = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftCpa");

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton_Clients.setText("Clients");
        jButton_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClientsActionPerformed(evt);
            }
        });

        jButton_Facturation.setText("Facturation");
        jButton_Facturation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FacturationActionPerformed(evt);
            }
        });

        jButton_Devis.setText("Devis");

        jButton_Providers.setText("Fournisseurs");
        jButton_Providers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProvidersActionPerformed(evt);
            }
        });

        jButton_Stock.setText("Stock");
        jButton_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StockActionPerformed(evt);
            }
        });

        jButton_Avoirs.setText("Avoirs");

        jButton_Invoices.setText("Invoices");
        jButton_Invoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InvoicesActionPerformed(evt);
            }
        });

        jMenu_Clients.setText("Clients");
        jMenu_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ClientsActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Clients);

        jMenu_Stock.setText("Stock");
        jMenuBar1.add(jMenu_Stock);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Avoirs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Clients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Providers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Devis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Facturation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Avoirs, jButton_Clients, jButton_Devis, jButton_Facturation, jButton_Invoices, jButton_Providers, jButton_Stock});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Facturation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Devis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Avoirs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Clients, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Providers, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Avoirs, jButton_Clients, jButton_Devis, jButton_Facturation, jButton_Invoices, jButton_Providers, jButton_Stock});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ClientsActionPerformed


    }//GEN-LAST:event_jMenu_ClientsActionPerformed

    private void jButton_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClientsActionPerformed
        clientView = defaultController.gestionClients();
        try {
            addFrame(clientView);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_ClientsActionPerformed

    private void jButton_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StockActionPerformed
        pieceView = defaultController.gestionStock();
        try {
            addFrame(pieceView);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_StockActionPerformed

    private void jButton_FacturationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FacturationActionPerformed
        invoicingView = defaultController.invoicing();
        try {
            addFrame(invoicingView);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_FacturationActionPerformed

    private void jButton_ProvidersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProvidersActionPerformed
        providerView = defaultController.managingProviders();
        try {
            addFrame(providerView);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_ProvidersActionPerformed

    private void jButton_InvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InvoicesActionPerformed
        invoiceView = defaultController.managingInvoices();
        try {
            addFrame(invoiceView);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_InvoicesActionPerformed

    public void addFrame(JInternalFrame view) throws PropertyVetoException {
        boolean open = false;

        for (Object frame : jDesktopPane.getAllFrames()) {
            if (frame.equals(view)) {
                view.setSelected(true);
                open = true;
                break;
            }
        }
        if (!open) {
            view.setVisible(true);
            jDesktopPane.add(view);
            view.setSelected(true);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Avoirs;
    private javax.swing.JButton jButton_Clients;
    private javax.swing.JButton jButton_Devis;
    private javax.swing.JButton jButton_Facturation;
    private javax.swing.JButton jButton_Invoices;
    private javax.swing.JButton jButton_Providers;
    private javax.swing.JButton jButton_Stock;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Clients;
    private javax.swing.JMenu jMenu_Stock;
    // End of variables declaration//GEN-END:variables
}
