/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.sysdev.softcpa.View;


import fr.sysdev.softcpa.constants.FR.*;
import java.beans.PropertyVetoException;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import javax.swing.plaf.DesktopPaneUI;
import org.springframework.stereotype.Component;


/**
 *
 * @author COPCGRE
 */
@Component
public class DefaultView extends javax.swing.JFrame {


    

    private Double salesRevenues;
    /**
     * Creates new form App
     */
    public DefaultView() {
        this.salesRevenues = 0.0;
        initComponents();
        this.setTitle("SoftCPA");
//        jDesktopPane.setUI(new DesktopPaneUI() {
//    @Override
//        public void installUI(JComponent c) {
////             TODO Auto-generated method stub
//            try {
//                UIManager.setLookAndFeel( "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//            super.installUI(c);
//        }   
//    });
        jLabel_Sales_Revenues.setText(Constants.Labels.SALES_REVENUES);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jButton_Clients = new javax.swing.JButton();
        jButton_Invoicing = new javax.swing.JButton();
        jButton_Devis = new javax.swing.JButton();
        jButton_Providers = new javax.swing.JButton();
        jButton_Stock = new javax.swing.JButton();
        jButton_Avoirs = new javax.swing.JButton();
        jButton_Invoices = new javax.swing.JButton();
        jLabel_Sales_Revenues = new javax.swing.JLabel();
        jLabel_Sales_Revenues_value = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Clients = new javax.swing.JMenu();
        jMenu_Stock = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftCpa");

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton_Clients.setText("Clients");

        jButton_Invoicing.setText("Facturation");

        jButton_Devis.setText("Devis");

        jButton_Providers.setText("Fournisseurs");

        jButton_Stock.setText("Stock");

        jButton_Avoirs.setText("Avoirs");

        jButton_Invoices.setText("Invoices");

        jLabel_Sales_Revenues.setText("jLabel1");

        jLabel_Sales_Revenues_value.setText("jLabel1");

        jMenu_Clients.setText("Clients");
        jMenu_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ClientsActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Clients);

        jMenu_Stock.setText("Stock");
        jMenuBar1.add(jMenu_Stock);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Avoirs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Clients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Providers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Devis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Invoicing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Sales_Revenues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Sales_Revenues_value)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Avoirs, jButton_Clients, jButton_Devis, jButton_Invoices, jButton_Invoicing, jButton_Providers, jButton_Stock});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Sales_Revenues)
                    .addComponent(jLabel_Sales_Revenues_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Invoicing, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Devis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Avoirs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Clients, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Providers, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Avoirs, jButton_Clients, jButton_Devis, jButton_Invoices, jButton_Invoicing, jButton_Providers, jButton_Stock});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ClientsActionPerformed


    }//GEN-LAST:event_jMenu_ClientsActionPerformed

    public void addFrame(JInternalFrame view) throws PropertyVetoException {
        boolean open = false;

        for (Object frame : jDesktopPane.getAllFrames()) {
            if (frame.equals(view)) {
                view.setSelected(true);
                view.toFront();
                view.setIcon(!view.isIcon());
                     //view.setMaximum(true);
 
                open = true;
                break;
            }
        }
        if (!open) {
            
            view.setIcon(false);
            view.setVisible(true);
            jDesktopPane.add(view);
            view.setSelected(true);
            view.toFront();
            
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Avoirs;
    private javax.swing.JButton jButton_Clients;
    private javax.swing.JButton jButton_Devis;
    private javax.swing.JButton jButton_Invoices;
    private javax.swing.JButton jButton_Invoicing;
    private javax.swing.JButton jButton_Providers;
    private javax.swing.JButton jButton_Stock;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel_Sales_Revenues;
    private javax.swing.JLabel jLabel_Sales_Revenues_value;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Clients;
    private javax.swing.JMenu jMenu_Stock;
    // End of variables declaration//GEN-END:variables

    public JButton getClientsBtn()
    {return jButton_Clients;
    }
    public JButton getStockBtn()
    {return jButton_Stock;
    }
    public JButton getProvidersBtn()
    {return jButton_Providers;
    }
    public JButton getInvoicingBtn()
    {return jButton_Invoicing;
    }
    public JButton getInvoicesBtn()
    {return jButton_Invoices;
    }

    public Double getSalesRevenues() {
        return salesRevenues;
    }

    public void setSalesRevenues(Double salesRevenues) {
        this.salesRevenues = salesRevenues;
    }
    
    public void displaySalesRevenues(){
        jLabel_Sales_Revenues_value.setText(this.salesRevenues+ " €");
    }

    private void prepareForm() {
       jButton_Invoicing.setText(Constants.Labels.INVOICING);
       jButton_Avoirs.setText(Constants.Labels.CREDIT_NOTE);
       jButton_Clients.setText(Constants.Labels.BTN_CLIENTS);
       jButton_Stock.setText(Constants.Labels.BTN_STOCK);
       jButton_Devis.setText(Constants.Labels.QUOTES);
       jButton_Providers.setText(Constants.Labels.BTN_PROVIDERS);
       jButton_Invoices.setText(Constants.Labels.INVOICES);
    }
}
