spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scpa_prod?createDatabaseIfNotExist=true
    username: scpa_prod_user
    password: Pq4s67Xa
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true