 spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scpa_dev?useSSL=false
    username: root
    password: 
#    url: jdbc:mysql://192.168.0.40:3306/scpa_dev?useSSL=false
#    username: adminmysql
#    password: 1234
#    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
      #generate_statistics: true
      statistics: true
      logging:
       level:
         org.hibernate.stat: DEBUG
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
 #   show-sql: true
    
 
 #   properties:
  #     javax:
   #      persistence:
    #      schema-generation:
     #       create-source: metadata
      #      scripts:
       #       action: create
        #      create-target: database_create.sql

    

    
