/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.sysdev.softcpa.View.Invoicing;


import fr.sysdev.softcpa.constants.Constants;
import fr.sysdev.softcpa.entity.Client;
import fr.sysdev.softcpa.entity.Part;
import fr.sysdev.softcpa.utils.predicates.PartsPredicates;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import static java.util.Locale.filter;
import java.util.Optional;
import java.util.Set;
import java.util.function.Predicate;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import static java.util.stream.Collectors.toList;
import java.util.stream.Stream;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.springframework.stereotype.Component;

/**
 *
 * @author f
 */
@Component
public class InvoicingView extends javax.swing.JInternalFrame {

    /**
     * Creates new form invoicingView
     */
    
    private List<Client> clients;
    private Client client ;
    private List<Part> parts ; 
    private Client seller;
    private ArrayList<String>clientsNamesList ;
    private DefaultListModel dlm;
    
    
    public InvoicingView() {
        initComponents();

    }

    public InvoicingView(List<Client> clients, List<Part> parts ) {
        this.clients = clients;
        this.parts = parts;
        initComponents();
       //prepareForm();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        idConvertor1 = new fr.sysdev.softcpa.utils.Converter.IdConvertor();
        clientStatusConverter1 = new fr.sysdev.softcpa.utils.Converter.ClientStatusConverter();
        jComboBox_Client = new javax.swing.JComboBox<>();
        jTextField_Search_Part = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel_Client_Id = new javax.swing.JLabel();
        jLabel_Client_Status = new javax.swing.JLabel();
        jLabel_Client_Name = new javax.swing.JLabel();
        jLabel_Client_Surname = new javax.swing.JLabel();
        jLabel_Client_CompanyName = new javax.swing.JLabel();
        jLabel_Client_Email = new javax.swing.JLabel();
        jLabel_Client_PhoneNumber = new javax.swing.JLabel();
        jLabel_Address_HouseNumber = new javax.swing.JLabel();
        jLabel_Address_Street = new javax.swing.JLabel();
        jLabel_Address_PostCode = new javax.swing.JLabel();
        jLabel_Address_City = new javax.swing.JLabel();
        jLabel_Client_CompanyID = new javax.swing.JLabel();
        jLabel_Client_Id_Value = new javax.swing.JLabel();
        jLabel_Client_Status_Value = new javax.swing.JLabel();
        jLabel_Client_Name_Value = new javax.swing.JLabel();
        jLabel_Client_Surname_Value = new javax.swing.JLabel();
        jLabel_Client_CompanyName_Value = new javax.swing.JLabel();
        jLabel_Client_Email_Value = new javax.swing.JLabel();
        jLabel_Client_PhoneNumber_Value = new javax.swing.JLabel();
        jLabel_Address_HouseNumber_Value = new javax.swing.JLabel();
        jLabel_Address_Street_Value = new javax.swing.JLabel();
        jLabel_Address_PostCode_Value = new javax.swing.JLabel();
        jLabel_Address_City_Value = new javax.swing.JLabel();
        jLabel_Client_CompanyID_Value = new javax.swing.JLabel();
        jButton_Refresh = new javax.swing.JButton();
        jLabel_Search_Part = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jComboBox_Client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Client.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ClientItemStateChanged(evt);
            }
        });

        jTextField_Search_Part.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Search_PartKeyReleased(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jList1);

        jLabel_Client_Id.setText("jLabel1");

        jLabel_Client_Status.setText("jLabel1");

        jLabel_Client_Name.setText("jLabel1");

        jLabel_Client_Surname.setText("jLabel1");

        jLabel_Client_CompanyName.setText("jLabel1");

        jLabel_Client_Email.setText("jLabel1");

        jLabel_Client_PhoneNumber.setText("jLabel1");

        jLabel_Address_HouseNumber.setText("jLabel1");

        jLabel_Address_Street.setText("jLabel1");

        jLabel_Address_PostCode.setText("jLabel1");

        jLabel_Address_City.setText("jLabel1");

        jLabel_Client_CompanyID.setText("jLabel1");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.id}"), jLabel_Client_Id_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(idConvertor1);
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.status}"), jLabel_Client_Status_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(clientStatusConverter1);
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.name}"), jLabel_Client_Name_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.surname}"), jLabel_Client_Surname_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.company.name}"), jLabel_Client_CompanyName_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.email}"), jLabel_Client_Email_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.phoneNumber}"), jLabel_Client_PhoneNumber_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.houseNumber}"), jLabel_Address_HouseNumber_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.street}"), jLabel_Address_Street_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.postCode}"), jLabel_Address_PostCode_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.city}"), jLabel_Address_City_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.company.cin}"), jLabel_Client_CompanyID_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jButton_Refresh.setText("jButton1");
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });

        jLabel_Search_Part.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Refresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Client_Id, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Client_Status, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Client_Name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Client_Surname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Client_CompanyName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Client_Email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Client_PhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Address_HouseNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Address_Street, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Address_PostCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Address_City, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Client_CompanyID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Client_Id_Value)
                            .addComponent(jLabel_Client_Status_Value)
                            .addComponent(jLabel_Client_Name_Value)
                            .addComponent(jLabel_Client_Surname_Value)
                            .addComponent(jLabel_Client_CompanyName_Value)
                            .addComponent(jLabel_Client_Email_Value)
                            .addComponent(jLabel_Client_PhoneNumber_Value)
                            .addComponent(jLabel_Address_HouseNumber_Value)
                            .addComponent(jLabel_Address_Street_Value)
                            .addComponent(jLabel_Address_PostCode_Value)
                            .addComponent(jLabel_Address_City_Value)
                            .addComponent(jLabel_Client_CompanyID_Value))))
                .addGap(42, 42, 42)
                .addComponent(jLabel_Search_Part)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField_Search_Part, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Search_Part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Refresh)
                    .addComponent(jLabel_Search_Part))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Client_Id)
                            .addComponent(jLabel_Client_Id_Value))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Client_Status)
                            .addComponent(jLabel_Client_Status_Value))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Client_Name)
                            .addComponent(jLabel_Client_Name_Value))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Client_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Client_Surname_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Client_CompanyName)
                            .addComponent(jLabel_Client_CompanyName_Value))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Client_Email)
                            .addComponent(jLabel_Client_Email_Value))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Client_PhoneNumber)
                            .addComponent(jLabel_Client_PhoneNumber_Value))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Address_HouseNumber)
                            .addComponent(jLabel_Address_HouseNumber_Value))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Address_Street)
                            .addComponent(jLabel_Address_Street_Value)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Address_PostCode)
                    .addComponent(jLabel_Address_PostCode_Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Address_City)
                    .addComponent(jLabel_Address_City_Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Client_CompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Client_CompanyID_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ClientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ClientItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
          Object item = evt.getItem();
            Optional<Client> clientOptional = clients.stream().filter((t) -> {
                
                return item.toString().equals(t.getName()+" "+t.getSurname());
            }).findAny();
            
            
               if(clientOptional.isPresent()){
                   client =clientOptional.get();
                   if(client.getStatus()==0) {showClientLabels(); hideCompanyInfo();}
                   else {showClientLabels();showCompanyInfo();}
                   refresh();
               }
               
               
               
               else{
                    hideClientLabels();
                   }
               
               
                
             System.out.println(item);
             System.out.println("client :"+ client);
             
       }
    }//GEN-LAST:event_jComboBox_ClientItemStateChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      
      prepareForm();
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
      prepareForm();
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jTextField_Search_PartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Search_PartKeyReleased
        
        search();
        
        
        
    }//GEN-LAST:event_jTextField_Search_PartKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.sysdev.softcpa.utils.Converter.ClientStatusConverter clientStatusConverter1;
    private fr.sysdev.softcpa.utils.Converter.IdConvertor idConvertor1;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JComboBox<String> jComboBox_Client;
    private javax.swing.JLabel jLabel_Address_City;
    private javax.swing.JLabel jLabel_Address_City_Value;
    private javax.swing.JLabel jLabel_Address_HouseNumber;
    private javax.swing.JLabel jLabel_Address_HouseNumber_Value;
    private javax.swing.JLabel jLabel_Address_PostCode;
    private javax.swing.JLabel jLabel_Address_PostCode_Value;
    private javax.swing.JLabel jLabel_Address_Street;
    private javax.swing.JLabel jLabel_Address_Street_Value;
    private javax.swing.JLabel jLabel_Client_CompanyID;
    private javax.swing.JLabel jLabel_Client_CompanyID_Value;
    private javax.swing.JLabel jLabel_Client_CompanyName;
    private javax.swing.JLabel jLabel_Client_CompanyName_Value;
    private javax.swing.JLabel jLabel_Client_Email;
    private javax.swing.JLabel jLabel_Client_Email_Value;
    private javax.swing.JLabel jLabel_Client_Id;
    private javax.swing.JLabel jLabel_Client_Id_Value;
    private javax.swing.JLabel jLabel_Client_Name;
    private javax.swing.JLabel jLabel_Client_Name_Value;
    private javax.swing.JLabel jLabel_Client_PhoneNumber;
    private javax.swing.JLabel jLabel_Client_PhoneNumber_Value;
    private javax.swing.JLabel jLabel_Client_Status;
    private javax.swing.JLabel jLabel_Client_Status_Value;
    private javax.swing.JLabel jLabel_Client_Surname;
    private javax.swing.JLabel jLabel_Client_Surname_Value;
    private javax.swing.JLabel jLabel_Search_Part;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Search_Part;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void loadClients() {
        dlm = new DefaultListModel<>();
       clientsNamesList = clientsNamesList();
       clientsNamesList.forEach( (String c)->{ jComboBox_Client.addItem(c);
            dlm.addElement(c);
                });       
       String[] clientsArray = new String[clientsNamesList.size()];
        
        
        clientsArray = clientsNamesList.toArray(clientsArray);
        jList1 = new JList(dlm);
    }
    
    private ArrayList<String>clientsNamesList(){ArrayList<String>cnl ;
        cnl = new ArrayList<>();
       clients.forEach( (Client c)-> {cnl.add(c.getName()+" "+c.getSurname());  });
       return cnl;
    }

    private void prepareForm() {
         jLabel_Client_Id.setText(Constants.Labels.CLIENT_ID);
        jLabel_Address_City.setText(Constants.Labels.CITY);
        jLabel_Address_HouseNumber.setText(Constants.Labels.HOUSE_NUMBER);
        jLabel_Address_PostCode.setText(Constants.Labels.POSTAL_CODE);
        jLabel_Client_Email.setText(Constants.Labels.EMAIL);
        jLabel_Client_Name.setText(Constants.Labels.NAME);
        jLabel_Client_PhoneNumber.setText(Constants.Labels.PHONE_NUMBER);
        jLabel_Client_Surname.setText(Constants.Labels.SURNAME);
       //jLabel_Client_Search.setText(Constants.Labels.SEARCH);
        jLabel_Address_Street.setText(Constants.Labels.STREET);
        jLabel_Client_Status.setText(Constants.Labels.CLIENT_STATUS);
        jLabel_Client_CompanyName.setText(Constants.Labels.COMPANY_NAME);
        jLabel_Client_CompanyID.setText(Constants.Labels.COMPANY_ID);
        jLabel_Search_Part.setText(Constants.Labels.SEARCH);
        jButton_Refresh.setText(Constants.Labels.REFRESH_BTN);
        jComboBox_Client.removeAllItems();
        jComboBox_Client.addItem(Constants.Messages.CHOOSE_CLIENT);
         loadClients();
        AutoCompleteDecorator.decorate(jComboBox_Client);
        hideClientLabels();
    }

    public List<Client> getClients() {
        return clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public List<Part> getParts() {
        return parts;
    }

    public void setParts(List<Part> parts) {
        this.parts = parts;
    }

    public Client getSeller() {
        return seller;
    }

    public void setSeller(Client seller) {
        this.seller = seller;
    }

    private void refresh() {
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.id}"), jLabel_Client_Id_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.status}"), jLabel_Client_Status_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.name}"), jLabel_Client_Name_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.surname}"), jLabel_Client_Surname_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.company.name}"), jLabel_Client_CompanyName_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.email}"), jLabel_Client_Email_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.phoneNumber}"), jLabel_Client_PhoneNumber_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.houseNumber}"), jLabel_Address_HouseNumber_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.street}"), jLabel_Address_Street_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.postCode}"), jLabel_Address_PostCode_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.address.city}"), jLabel_Address_City_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${client.company.cin}"), jLabel_Client_CompanyID_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        bindingGroup.bind();
    }


    
    public void hideCompanyInfo() {
        jLabel_Client_CompanyName.setVisible(false);
        jLabel_Client_CompanyID.setVisible(false);
        jLabel_Client_CompanyName_Value.setVisible(false);
        jLabel_Client_CompanyID_Value.setVisible(false);
    }
    
    public void showCompanyInfo() {
        jLabel_Client_CompanyName.setVisible(true);
        jLabel_Client_CompanyID.setVisible(true);
         jLabel_Client_CompanyName_Value.setVisible(true);
        jLabel_Client_CompanyID_Value.setVisible(true);

    }
    
    public void hideClientLabels(){
        jLabel_Client_Id_Value.setVisible(false);
        jLabel_Address_City_Value.setVisible(false);
        jLabel_Address_HouseNumber_Value.setVisible(false);
        jLabel_Address_PostCode_Value.setVisible(false);
        jLabel_Client_Email_Value.setVisible(false);
        jLabel_Client_Name_Value.setVisible(false);
        jLabel_Client_PhoneNumber_Value.setVisible(false);
        jLabel_Client_Surname_Value.setVisible(false);
       //jLabel_Client_Search.setText(Constants.Labels.SEARCH);
        jLabel_Address_Street_Value.setVisible(false);
        jLabel_Client_Status_Value.setVisible(false);
        jLabel_Client_CompanyName_Value.setVisible(false);
        jLabel_Client_CompanyID_Value.setVisible(false);
        
        jLabel_Client_Id.setVisible(false);
        jLabel_Address_City.setVisible(false);
        jLabel_Address_HouseNumber.setVisible(false);
        jLabel_Address_PostCode.setVisible(false);
        jLabel_Client_Email.setVisible(false);
        jLabel_Client_Name.setVisible(false);
        jLabel_Client_PhoneNumber.setVisible(false);
        jLabel_Client_Surname.setVisible(false);
       //jLabel_Client_Search.setText(Constants.Labels.SEARCH);
        jLabel_Address_Street.setVisible(false);
        jLabel_Client_Status.setVisible(false);
        jLabel_Client_CompanyName.setVisible(false);
        jLabel_Client_CompanyID.setVisible(false);
    }
    
    public void showClientLabels(){
         jLabel_Client_Id.setVisible(true);
        jLabel_Address_City.setVisible(true);
        jLabel_Address_HouseNumber.setVisible(true);
        jLabel_Address_PostCode.setVisible(true);
        jLabel_Client_Email.setVisible(true);
        jLabel_Client_Name.setVisible(true);
        jLabel_Client_PhoneNumber.setVisible(true);
        jLabel_Client_Surname.setVisible(true);
       //jLabel_Client_Search.setText(Constants.Labels.SEARCH);
        jLabel_Address_Street.setVisible(true);
        jLabel_Client_Status.setVisible(true);
        jLabel_Client_CompanyName.setVisible(true);
        
        jLabel_Client_CompanyID_Value.setVisible(true);
        jLabel_Client_Id_Value.setVisible(true);
        jLabel_Address_City_Value.setVisible(true);
        jLabel_Address_HouseNumber_Value.setVisible(true);
        jLabel_Address_PostCode_Value.setVisible(true);
        jLabel_Client_Email_Value.setVisible(true);
        jLabel_Client_Name_Value.setVisible(true);
        jLabel_Client_PhoneNumber_Value.setVisible(true);
        jLabel_Client_Surname_Value.setVisible(true);
       //jLabel_Client_Search.setText(Constants.Labels.SEARCH);
        jLabel_Address_Street_Value.setVisible(true);
        jLabel_Client_Status_Value.setVisible(true);
        jLabel_Client_CompanyName_Value.setVisible(true);
        jLabel_Client_CompanyID_Value.setVisible(true);
    }
    
    public JButton getRefreshBtn(){
    
    return jButton_Refresh;
    }

    private void search() {
        String s = jTextField_Search_Part.getText().toUpperCase();
        List<Part> filter = PartsPredicates.filterParts(parts,PartsPredicates.refOrEanOrDesignationOrBrandContains(s));
       
        filter.forEach(System.out::println);
        
        
    }
    
    
    
    
    
    
}
