/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.sysdev.softcpa.View.Client;

import fr.sysdev.softcpa.Controller.Client.ClientController;
import fr.sysdev.softcpa.constants.Constants;
import fr.sysdev.softcpa.entity.Address;
import fr.sysdev.softcpa.entity.Client;
import java.awt.Color;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author COPCGRE
 */
@Slf4j
@Component
@Scope
public class ClientView extends javax.swing.JInternalFrame {
    @Autowired
    ClientController clientController ;
    /**
     * Creates new form ClientView
     */
    public List<Client> clients ;
    public Client client ;
    
    
    
    public ClientView() {
        client = new Client();
        initComponents();
        
        
        
    }
    public ClientView(List<Client> clients ) {
        client = new Client();
        this.clients = clients;
        initComponents();
        prepareForm();
        resetInterface();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        idConvertor1 = new fr.sysdev.softcpa.utils.IdConvertor();
        jTextField_Client_Name = new javax.swing.JTextField();
        jTextField_Client_Surname = new javax.swing.JTextField();
        jTextField_Client_Email = new javax.swing.JTextField();
        jTextField_Client_PhoneNumber = new javax.swing.JTextField();
        jTextField_Address_HouseNumber = new javax.swing.JTextField();
        jTextField_Address_Street = new javax.swing.JTextField();
        jTextField_Address_PostCode = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_client = new javax.swing.JTable();
        jTextField_Address_City = new javax.swing.JTextField();
        jLabel_Client_Name = new javax.swing.JLabel();
        jLabel_Client_Surname = new javax.swing.JLabel();
        jLabel_Client_PhoneNumber = new javax.swing.JLabel();
        jLabel_Client_Email = new javax.swing.JLabel();
        jLabel_Address_Street = new javax.swing.JLabel();
        jLabel_Address_HouseNumber = new javax.swing.JLabel();
        jLabel_Address_PostCode = new javax.swing.JLabel();
        jLabel_Address_City = new javax.swing.JLabel();
        jTextField_Client_Search = new javax.swing.JTextField();
        jLabel_Client_Search = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des clients");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.name}"), jTextField_Client_Name, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.surname}"), jTextField_Client_Surname, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.email}"), jTextField_Client_Email, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.phoneNumber}"), jTextField_Client_PhoneNumber, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.address.houseNumber}"), jTextField_Address_HouseNumber, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.address.street}"), jTextField_Address_Street, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.address.postCode}"), jTextField_Address_PostCode, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jButton_add.setText("New");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_remove.setText("Delete");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");

        jButton_update.setText("Modify");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jTable_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${clients}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable_client);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${surname}"));
        columnBinding.setColumnName("Surname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${phoneNumber}"));
        columnBinding.setColumnName("Phone Number");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(fr.sysdev.softcpa.entity.Address.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_clientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_client);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable_client, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.address.city}"), jTextField_Address_City, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel_Client_Name.setText("jLabel1");

        jLabel_Client_Surname.setText("jLabel1");

        jLabel_Client_PhoneNumber.setText("jLabel1");

        jLabel_Client_Email.setText("jLabel1");

        jLabel_Address_Street.setText("jLabel1");

        jLabel_Address_HouseNumber.setText("jLabel1");

        jLabel_Address_PostCode.setText("jLabel1");

        jLabel_Address_City.setText("jLabel1");

        jLabel_Client_Search.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Client_Surname)
                                    .addComponent(jLabel_Client_PhoneNumber)
                                    .addComponent(jLabel_Client_Email)
                                    .addComponent(jLabel_Client_Name))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_Client_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Client_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_Client_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Client_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_Address_PostCode)
                                    .addComponent(jLabel_Address_City)
                                    .addComponent(jLabel_Address_Street)
                                    .addComponent(jLabel_Address_HouseNumber))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Address_HouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Address_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Address_PostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Address_City, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_Client_Search)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Client_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Client_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Client_Search))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Client_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Client_Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Client_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Client_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Client_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Client_Email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Client_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Client_PhoneNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Address_HouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Address_HouseNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Address_Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Address_Street))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Address_PostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Address_PostCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Address_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Address_City)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_remove)
                    .addComponent(jButton_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_update)
                    .addComponent(jButton_cancel))
                .addGap(72, 72, 72))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed

        Iterator<Client> iteratorClient = clients.iterator();
        int index = 0;
        boolean found = false;

        
        clients.forEach((Client c)->{
            if(Objects.equals(c.getId(), client.getId())){
                c = client; 
                }
        });
        
    
      bindingClientTable();
        jTable_client.setSelectionBackground(Color.blue);
        jTable_client.setSelectionForeground(Color.white);
        
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed


       clients.removeIf(c -> {
            return Objects.equals(c.getId(), client.getId());
        });

       bindingClientTable();
       resetInterface();


    }//GEN-LAST:event_jButton_removeActionPerformed

 
    private void jTable_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_clientMouseClicked
        int selectedRow = jTable_client.getSelectedRow();
        Long id = (Long) (jTable_client.getModel().getValueAt(selectedRow, 0));

        getClientForm(id);

        jTable_client.setSelectionBackground(Color.blue);
        jTable_client.setSelectionForeground(Color.white);
        updateInterface();
    }//GEN-LAST:event_jTable_clientMouseClicked

    public void getClientForm(Long id) {
        Address address = new Address();
        address.setCity(jTextField_Address_City.getText());
        address.setHouseNumber(jTextField_Address_HouseNumber.getText());
        address.setPostCode(jTextField_Address_PostCode.getText());
        address.setStreet(jTextField_Address_Street.getText());
        
        String name = jTextField_Client_Name.getText();
        String surname = jTextField_Client_Surname.getText();
        String phone = jTextField_Client_PhoneNumber.getText();
        String email = jTextField_Client_Email.getText();
        
        client.setId(id);
        client.setAddress(address);
        client.setName(name);
        client.setSurname(surname);
        client.setPhoneNumber(phone);
        client.setEmail(email);
        
    
    }

    public Client getClientForm() {
        
        
        Address address = new Address();
        address.setCity(jTextField_Address_City.getText());
        address.setHouseNumber(jTextField_Address_HouseNumber.getText());
        address.setPostCode(jTextField_Address_PostCode.getText());
        address.setStreet(jTextField_Address_Street.getText());
        
        String name = jTextField_Client_Name.getText();
        String surname = jTextField_Client_Surname.getText();
        String phone = jTextField_Client_PhoneNumber.getText();
        String email = jTextField_Client_Email.getText();
        
        
        client.setAddress(address);
        client.setName(name);
        client.setSurname(surname);
        client.setPhoneNumber(phone);
        client.setEmail(email);
        
     return client;
    }
    
    
    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
      
        getClientForm(clients.get(clients.size()-1).getId()+1);
        clients.add(client);
        log.debug(" size "+clients.size()+
                "\n index client "+clients.indexOf(client));
        bindingClientTable(); 
    }//GEN-LAST:event_jButton_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.sysdev.softcpa.utils.IdConvertor idConvertor1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel_Address_City;
    private javax.swing.JLabel jLabel_Address_HouseNumber;
    private javax.swing.JLabel jLabel_Address_PostCode;
    private javax.swing.JLabel jLabel_Address_Street;
    private javax.swing.JLabel jLabel_Client_Email;
    private javax.swing.JLabel jLabel_Client_Name;
    private javax.swing.JLabel jLabel_Client_PhoneNumber;
    private javax.swing.JLabel jLabel_Client_Search;
    private javax.swing.JLabel jLabel_Client_Surname;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_client;
    private javax.swing.JTextField jTextField_Address_City;
    private javax.swing.JTextField jTextField_Address_HouseNumber;
    private javax.swing.JTextField jTextField_Address_PostCode;
    private javax.swing.JTextField jTextField_Address_Street;
    private javax.swing.JTextField jTextField_Client_Email;
    private javax.swing.JTextField jTextField_Client_Name;
    private javax.swing.JTextField jTextField_Client_PhoneNumber;
    private javax.swing.JTextField jTextField_Client_Search;
    private javax.swing.JTextField jTextField_Client_Surname;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public List<Client> getClients() {
        return clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }

    private void bindingClientTable (){
         org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${clients}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable_client);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${surname}"));
        columnBinding.setColumnName("Surname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${phoneNumber}"));
        columnBinding.setColumnName("Phone Number");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(fr.sysdev.softcpa.entity.Address.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
}
    
    
    
    public JButton getRemoveBtn() {
        return jButton_remove;
    }
    
     public JButton getAddBtn() {
        return jButton_add;
    }

     public JButton getUpdateBtn() {
        return jButton_update;
    } 
     
     
    private void prepareForm() {
        jLabel_Address_City.setText(Constants.CITY);
        jLabel_Address_HouseNumber.setText(Constants.HOUSE_NUMBER);
        jLabel_Address_PostCode.setText(Constants.POSTAL_CODE);
        jLabel_Client_Email.setText(Constants.EMAIL);
        jLabel_Client_Name.setText(Constants.NAME);
        jLabel_Client_PhoneNumber.setText(Constants.PHONE_NUMBER);
        jLabel_Client_Surname.setText(Constants.SURNAME);
        jLabel_Client_Search.setText(Constants.SEARCH);
        jLabel_Address_Street.setText(Constants.STREET);
        jButton_add.setText(Constants.ADD_BTN);
        jButton_remove.setText(Constants.REMOVE_BTN);
        jButton_update.setText(Constants.UPDATE_BTN);
    }
    
    private void resetInterface() {
        searchInterface();
        jTextField_Client_Search.setText("");
       
    }
    
    private void searchInterface() {
        
       jTextField_Address_City.setText("");
       jTextField_Address_HouseNumber.setText("");
       jTextField_Address_PostCode.setText("");
       jTextField_Address_Street.setText("");
       jTextField_Client_Email.setText("");
       jTextField_Client_Name.setText("");
       jTextField_Client_PhoneNumber.setText("");
       jTextField_Client_Surname.setText("");
       jTextField_Client_Surname.setText("");
       
       jButton_add.setVisible(true);
       jButton_remove.setVisible(false);
       jButton_update.setVisible(false);
       jButton_cancel.setVisible(false);
    }
    
    
      private void updateInterface() {  
       jButton_add.setVisible(true);
       jButton_remove.setVisible(true);
       jButton_update.setVisible(true);
       jButton_cancel.setVisible(false);
    }
    
    
    
    public Client getClient() {
        return getClientForm();
    }

    public void setClient(Client client) {
        this.client = client;
    }

    
}
